---
title: "MY WEBSITE"
date: 2022-04-06
---
title: My Website
author: Dominik Soltysiak
email: dominik1.soltysiak@wp.pl
description: > This is my website 

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
